### ISSUE TITLE
Error enabling v1.0.2 in REDCap 8.10.6

### ISSUE THREAD

**Issue by targetpharma** [lsgs/redcap-survey-link-lookup#1]
I was able to successful install and enable v1.0.2 of the module in a REDCap 8.7.0 instance. 

But on my REDCap 8.10.6 instance, after following the same installation steps, I receive the following error dialog when attempting to enable the module:

![image](https://user-images.githubusercontent.com/20141935/53646826-2f27fc80-3c0a-11e9-9cda-1f925b2c3c83.png)

There are several other modules in my REDCap 8.10.6 instance that have been successfully enabled.

If there are additional logs you would like me to provide or other steps/actions I can take to help debug please do let me know.

**Comment by lsgs** [comment]
We had this before when the EM framework was not handling the default settings in the config.json correctly.

Can you remove the default values from the config and re-try enabling the module (and then re-enter the values in module configuration page)?

https://community.projectredcap.org/questions/34984/external-module-survey-link-lookup-enable-error.html

https://community.projectredcap.org/questions/33906/exception-while-enabling-module-cannot-create-modu.html

Or just upgrade to 8.11.0+ where the functionality of this module was incorporated within REDCap.

**Comment by targetpharma** [comment]
Thanks! Working now.
